### ISSUE TITLE
Some missing cards

### ISSUE THREAD

**Issue by shadowfox87** [Yuzurisa/ygopro-rush-duel#3]
120170201 The Fire Dragon
120170202 Flower Fang Spores
120170203 Flower Fang Comeback
120170204 Flower Fang Kunoichi Etranzer
120170205 Flower Fang Shadow Strike
120170206 Flower Fang Shinobi Gatring
120170207 Flower Fang Wolf Kurobana
120170208 Flower Fang Warrior Rindo
120170209 True Flower Fang Kunoichi Garrand

The cards from Deck Modification Pack - Dynamic Eternal Live!! (RD/KP05-JP) are left to do.

**Comment by jianmos90** [comment]
Flower Fang Spores and Flower Fang Comeback temporarily use animation effects

**Comment by shadowfox87** [comment]
thank you
