### ISSUE TITLE
list unscripted cards 

### ISSUE THREAD

**Issue by doobovenom** [Yuzurisa/ygopro-rush-duel#7]
1. nightbringer dragon  (120185001)
2. saikyo beast rhino cannon  (120109008)
3. saikyo flag beast surge bicorn  (120181011)
4. The☆Star Dragon  (120109009)
5. mystery handcuffs (120192032)
6. stop defense (120190021)

**Comment by jianmos90** [comment]
- [ √ ] nightbringer dragon (120185001)
- [ √ ] saikyo beast rhino cannon (120109008)
- [ √ ] saikyo flag beast surge bicorn (120181011)
- [ √ ] The☆Star Dragon (120109009)
- [ ! ] mystery handcuffs (120192032) -> Now Use 120186032
- [ ! ] stop defense (120190021) -> Now Use 120187022

重复的卡，我使用最小的编号
Duplicate cards, I use the smallest number

**Comment by shadowfox87** [comment]
Done thank you.
